# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 18:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import managerData.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cara_Perolehan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_perolehan', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_instansi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Kategori_Karya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Koleksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_inventaris', models.CharField(max_length=50)),
                ('no_urut_koleksi_seniman', models.IntegerField()),
                ('judul_karya', models.CharField(max_length=1000)),
                ('deskripsi_karya', models.TextField()),
                ('tahun_pembuatan', models.IntegerField()),
                ('foto', models.FileField(upload_to=managerData.models.foto_file_path)),
                ('nomor_slide_negatif', models.CharField(max_length=200)),
                ('media', models.TextField()),
                ('ukuran', models.TextField()),
                ('harga', models.IntegerField()),
                ('waktu_edit_terakhir', models.DateTimeField()),
                ('input_time', models.DateTimeField()),
                ('tahun_perolehan', models.IntegerField()),
                ('tanda_tangan_seniman', models.BooleanField(default=False)),
                ('nomor_perolehan', models.IntegerField()),
                ('no_urut_koleksi', models.IntegerField()),
                ('no_registrasi', models.CharField(max_length=100)),
                ('cara_perolehan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerData.Cara_Perolehan')),
                ('diedit_oleh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diedit_oleh', to=settings.AUTH_USER_MODEL)),
                ('diperoleh_dari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diperoleh_dari', to='managerData.Instansi')),
                ('id_instansi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_instansi', to='managerData.Instansi')),
            ],
        ),
        migrations.CreateModel(
            name='Kondisi_Karya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_kondisi', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Lokasi_Penyimpanan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ruangan', models.CharField(max_length=100)),
                ('jenis_rak', models.CharField(max_length=50)),
                ('no_urut_rak', models.CharField(max_length=50)),
                ('no_urut_karya_rak', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pegawai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('jabatan', models.CharField(max_length=200)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Seniman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('biografi', models.TextField()),
                ('tahun_lahir', models.DateField(null=True)),
                ('tahun_meninggal', models.DateField(null=True)),
                ('narahubung', models.CharField(max_length=500, null=True)),
                ('alamat', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Status_Karya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='koleksi',
            name='id_seniman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerData.Seniman'),
        ),
        migrations.AddField(
            model_name='koleksi',
            name='input_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='koleksi',
            name='kategori_karya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerData.Kategori_Karya'),
        ),
        migrations.AddField(
            model_name='koleksi',
            name='kondisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerData.Kondisi_Karya'),
        ),
        migrations.AddField(
            model_name='koleksi',
            name='kurator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kurator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='koleksi',
            name='lokasi_penyimpanan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerData.Lokasi_Penyimpanan'),
        ),
        migrations.AddField(
            model_name='koleksi',
            name='status_karya',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managerData.Status_Karya'),
        ),
    ]
